# ndarrayの演算

In [1]:
import numpy as np

In [2]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [10]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array3 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

In [11]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [12]:
array3 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [13]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = 3

In [14]:
ndarray + a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])