# Shape

In [2]:
import numpy as np

In [5]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
ndarray.shape

(3, 2)

In [7]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [12]:
print(ndarray1.shape)

(3,)


In [13]:
print(ndarray2.shape)

(1, 3)


In [14]:
np.expand_dims(ndarray1, axis=0)

array([[1, 2, 3]])

In [16]:
expand_ndarray = np.expand_dims(ndarray1, axis=1)

In [17]:
expand_ndarray.shape

(3, 1)

In [18]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [19]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])