# Indexing と Slicing

In [1]:
import numpy as np

In [2]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [3]:
ndarray[0]

1

In [4]:
ndarray[-1]

4

In [5]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
ndarray[0, 1]

2

In [10]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [11]:
ndarray[1:3]

array([2, 3])

In [16]:
ndarray[:]

array([1, 2, 3, 4])

In [17]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [18]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
ndarray[:3, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [21]:
ndarray[:3][2:]

array([[ 9, 10, 11, 12]])