## np.arange(), np.linspace(), np.logspace()

In [2]:
import numpy as np

In [6]:
np.arange(start=0, stop=5, step=1)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(3, 15, 2)

array([ 3,  5,  7,  9, 11, 13])

In [8]:
list(range(3, 15, 2))

[3, 5, 7, 9, 11, 13]

In [9]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [14]:
# 0から3まで10等分した値が返ってくる
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [15]:
# 10^0から10^3までを10等分した値が返ってくる
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [ ]:
np.logspace(0, 3, 10, endspace)

In [17]:
10 ** 0.33333

2.1544181541980056