# np.randomを使って乱数を生成

## np.random.rand()

In [1]:
import numpy as np

In [7]:
np.random.rand()

0.03926018873361359

In [6]:
np.random.rand(3, 4)

array([[0.75009375, 0.06722657, 0.4148797 , 0.71987222],
       [0.56077369, 0.38193044, 0.99834388, 0.01280376],
       [0.42215006, 0.92706152, 0.84151423, 0.89408435]])

## np.random.seed

In [15]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [19]:
np.random.rand()

0.14675589081711304

## np.random.randn()

In [26]:
np.random.randn(2, 3)

array([[-0.85990661,  1.77260763, -1.11036305],
       [ 0.18121427,  0.56434487, -0.56651023]])

In [27]:
np.random.normal(10, 1)

10.729975596413844

## np.random.randint()

In [29]:
np.random.randint(10, 100, (2, 3))

array([[70, 91, 18],
       [98, 23, 57]])

## np.random.choice()

In [32]:
a = [1, 2, 3, 4, 5, 6]
np.random.choice(a)

1

In [34]:
index_pool = np.arange(0, 10, 2)
index_pool

array([0, 2, 4, 6, 8])

In [37]:
idx = np.random.choice(index_pool)
idx

2