# 数学で使う便利関数

In [1]:
import numpy as np

In [2]:
# 平方根 square root
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [6]:
# log logarithm
x = np.linspace(1, 10, 10)
x
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [9]:
# 指数関数 exponential function
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [13]:
# 合計 summation
array = np.arange(1, 11)
array
np.sum(array)

55

In [15]:
ndarray = array.reshape(2, 5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
np.sum(ndarray, axis=1)

array([15, 40])

In [19]:
# 絶対値 absolute value
array = np.arange(-10, 0)
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [20]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])