# その他の便利関数

In [1]:
import numpy as np

### np.clip

In [2]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

# numpy array の conditon

In [4]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.where

In [5]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [6]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [7]:
array[array>3]

array([4, 5, 6, 7, 8, 9])

In [8]:
ndarray = array.reshape(2, 5)
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [9]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [10]:
(ndarray > 3).all()

False

In [11]:
(ndarray > 3).any()

True

### np.unique()

In [15]:
array = np.array([1, 1, 2, 3, 4, 2, 3, 4, 5])
array

array([1, 1, 2, 3, 4, 2, 3, 4, 5])

In [16]:
# 各要素のカウントを返してくれる
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

### np.bincount()

In [17]:
# 0, 1, 2, ... のカウントを返してくれる
np.bincount(array)

array([0, 2, 2, 2, 2, 1])